### ISSUE TITLE
UI doesn't work with Thorntail 2.3.0.Final

### ISSUE THREAD

**Issue by kret11** [microprofile-extensions/health-ext#1]
System and JVM probes load successfully, but not UI.

**Comment by phillip-kruger** [comment]
Let me have a look, i'll get back to you

**Comment by phillip-kruger** [comment]
Hi, I am struggling to recreate the issue. I have updated the example app to 2.3.0.Final and it's still working. Can you please see if the example app is running on your PC ?

https://github.com/microprofile-extensions/health-ext/tree/master/health-example

Let me know.

Thanks

**Comment by kret11** [comment]
https://pastebin.com/0036DZnh
running with 'mvn thorntail:run'

**Comment by phillip-kruger** [comment]
So in the example I explicitly set the context path to be the artifactId,
That means the URL is http://localhost:8080**/health-example/**health-ui/

In your example you are using the naked path, so try http://localhost:8080/health-ui/

Let me know

**Comment by kret11** [comment]
health-ui is not even loaded.
https://pastebin.com/raw/i0MEYgq2
(hytrix exception is one more problem, but its not connected with microprofile extensions)

**Comment by phillip-kruger** [comment]
Ok, the example is working fine with mvn thorntail:run, can you share your project ? Or recreate it so that I can look at it ?

**Comment by phillip-kruger** [comment]
Maybe try adding the servlet fraction, not sure what it is, I think undertow, as the UI loads webjars that uses servlet. I'll also try that later. Let me know

**Comment by kret11** [comment]
https://github.com/kret11/thorntail-microprofile-errors

**Comment by phillip-kruger** [comment]
Great! I'll have a look a bit later

**Comment by phillip-kruger** [comment]
Ok, this is a sneaky one. Because you have:

`@ApplicationPath("/")` in JaxRsActivator
and
`@Path("/")` in Endpoint

all requests (except the paths reserved for the application server, like /healh and /metrics) goes to your endpoint, so when you go to /health-ui it goes to your endpoint and can not resolve.

If you change to publish your REST services under, lets say /api, so:

`@ApplicationPath("/api")` 

It will work fine, then /health-ui goes to the static HTML page that is included in the microprofile-ext health-ui jar file

Hope that helps.

**Comment by kret11** [comment]
well. sorry for taking your time and thanks for checking it out

**Comment by phillip-kruger** [comment]
No problem ;)

**Comment by phillip-kruger** [comment]
Also consider to change you pom to be more specific, ie do not add microprofile and thorntail:full, rather do:```


<dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>microprofile-health</artifactId>
		</dependency>
                <dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>microprofile-openapi</artifactId>
		</dependency>
                <dependency>
			<groupId>io.thorntail</groupId>
			<artifactId>microprofile-metrics</artifactId>
		</dependency>
                

```

**Comment by kret11** [comment]
sure, when writing microservices we should minimalise everything

**Comment by phillip-kruger** [comment]
Yes, it might also get rid of some errors, like the hystrics / fautl tolerance clash.
On another note, check out microprofile-ext|swagger-ui as an alternative for swagger-webapp. It gives you some options to white-label.

https://github.com/microprofile-extensions/openapi-ext/blob/master/swagger-ui/README.md

**Comment by kret11** [comment]
thanks. its even more beautiful and does not cause ft clash :p
