### ISSUE TITLE
[health-ui] in case of 503 status, health-ui does not report failure

### ISSUE THREAD

**Issue by dinhhoang1995** [microprofile-extensions/health-ext#2]
health-ui is green when response status is 503.
It does not behave as described in section "Appendix B: Response Codes and status mappings" of the specification document.
[https://github.com/eclipse/microprofile-health/blob/2.0.2/spec/src/main/asciidoc/protocol-wireformat.adoc](https://github.com/eclipse/microprofile-health/blob/2.0.2/spec/src/main/asciidoc/protocol-wireformat.adoc)

Request | HTTP Status | JSON Payload | State | Comment
-- | -- | -- | -- | --
/health/live   /health/ready   /health | 503 | Yes | Down | Check failed
/health/live   /health/ready   /health | 503 | Yes | Down | Check with procedures expected but not yet installed. See With procedures expected but not yet installed into the runtime

@tnmtechnologies

**Comment by phillip-kruger** [comment]
Cool. Yes I think the UI just look at the json. I will look at this a.s.a.p (or if you want to and do a PR that might be quicker)

**Comment by phillip-kruger** [comment]
Can you please look at the latest SNAPSHOT and see if that works better for you ? Once you are happy we can release to maven central

**Comment by dinhhoang1995** [comment]
Thank you for your fix proposal.
In our project, we use Thorntail 2.5.0 which is compatible with MicroProfile 3.0 and Health Check 2.0.
There are changes in the response text.
I changed from "outcome" to "status", and from "state" to "status" of the "checks" attribute.
Then it works for me.
Without these changes, it does not work.
![image](https://user-images.githubusercontent.com/32743407/65692299-96a80c80-e072-11e9-9880-635a4c03a6c4.png)

**Comment by phillip-kruger** [comment]
Ok yes, this has not been updated for health 2.0. will do that asap
